---
# tasks file for reboot-if-required

- name: Ensure WinRM starts when the system has settled and is ready to work reliably
  win_service:
    name: WinRM
    start_mode: delayed

- name: Ensure Windows is rebooted, if required
  win_reboot:
    reboot_timeout: "{{ reboot_timeout }}"
  when: res.reboot_required

- name: Ensure that the netlogon service has started, before running the next task
  win_reboot:
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
